import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import pg from "pg";
import bcrypt from "bcryptjs";

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
  // ═══ Eski verileri temizle ═══
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.productImage.deleteMany();
  await prisma.productVariant.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();
  await prisma.discountCode.deleteMany();
  console.log("Eski veriler temizlendi");

  // ═══ KATEGORİLER ═══
  const categories = [
    { name: "Kolyeler", slug: "kolyeler", sortOrder: 1, description: "925 ayar gümüş ve özel tasarım kolye koleksiyonu" },
    { name: "Küpeler", slug: "kupeler", sortOrder: 2, description: "El yapımı, zarif küpe tasarımları" },
    { name: "Bileklikler", slug: "bileklikler", sortOrder: 3, description: "Su yolu, şahmeran ve özel tasarım bileklikler" },
    { name: "Yüzükler", slug: "yuzukler", sortOrder: 4, description: "Ayarlanabilir beden, zirkon taş yüzükler" },
    { name: "Şahmeran", slug: "sahmeran", sortOrder: 5, description: "Geleneksel şahmeran bileklik koleksiyonu" },
  ];

  const catMap: Record<string, string> = {};
  for (const cat of categories) {
    const c = await prisma.category.create({ data: cat });
    catMap[cat.slug] = c.id;
  }
  console.log("Kategoriler oluşturuldu");

  // ═══ ADMİN KULLANICI ═══
  const adminPassword = await bcrypt.hash("admin123", 12);
  await prisma.user.upsert({
    where: { email: "admin@bycollection.com" },
    update: {},
    create: {
      name: "Admin",
      email: "admin@bycollection.com",
      hashedPassword: adminPassword,
      role: "ADMIN",
    },
  });
  console.log("Admin kullanıcı oluşturuldu");

  // ═══ ÜRÜNLER ═══
  const products = [
    // ── KOLYELER ──
    {
      name: "Deuce 925 Ayar Gümüş Kolye",
      slug: "deuce-925-ayar-gumus-kolye",
      categoryId: catMap.kolyeler,
      description: "925 ayar gümüşten üretilen Deuce kolye, sportif ve zarif tasarımıyla günlük kullanıma uygun. İnce zincir detayı ve minimal çizgileriyle her kombine uyum sağlar.",
      shortDescription: "925 ayar gümüş, sportif ve zarif tasarım",
      price: 1200,
      sku: "LUM-KLY-001",
      stockQuantity: 15,
      isFeatured: true,
      material: "925 Ayar Gümüş",
      weight: "4.2g",
      has3dModel: true,
      images: [{ imageUrl: "/images/products/kolye-altin-damla.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "Golden Serve Kolye",
      slug: "golden-serve-kolye",
      categoryId: catMap.kolyeler,
      description: "Kapaklı Tenis Raketi Kolye – 925 Ayar Gümüş. Minimal tasarımı ve Okyanus Mavisi zirkon taş detayıyla göz kamaştıran bu kolye, tenis tutkunları için özel olarak tasarlandı.",
      shortDescription: "925 ayar gümüş, Okyanus Mavisi zirkon taş detaylı",
      price: 1700,
      sku: "LUM-KLY-002",
      stockQuantity: 10,
      isFeatured: true,
      material: "925 Ayar Gümüş, Zirkon Taş",
      weight: "5.1g",
      has3dModel: true,
      images: [{ imageUrl: "/images/products/kolye-ay-isigi.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "Tennis Racket Kolye",
      slug: "tennis-racket-kolye",
      categoryId: catMap.kolyeler,
      description: "925 Ayar Gümüş Özel Tasarım Tenis Raketi Kolyesi. Tenis tutkunları için zarafet ve şıklığı bir araya getiren bu özel parça, her anınıza ışıltı katar.",
      shortDescription: "925 ayar gümüş özel tasarım tenis raketi kolyesi",
      price: 1172,
      sku: "LUM-KLY-003",
      stockQuantity: 20,
      isFeatured: true,
      material: "925 Ayar Gümüş",
      weight: "3.8g",
      has3dModel: true,
      images: [{ imageUrl: "/images/products/kolye-kalp-elmas.svg", isPrimary: true }],
      variants: [
        { name: "Altın", variantType: "color", priceModifier: 0, stockQuantity: 10 },
        { name: "Gümüş", variantType: "color", priceModifier: 0, stockQuantity: 10 },
      ],
    },
    {
      name: "Stella Çok Renkli Kolye",
      slug: "stella-cok-renkli-kolye",
      categoryId: catMap.kolyeler,
      description: "Zirkon taşlarla süslenmiş çok renkli tasarım. Kalıcı parlaklığını koruyan özel kaplama ile uzun ömürlü kullanım sunar.",
      shortDescription: "Zirkon taş detaylı çok renkli kolye",
      price: 490,
      sku: "LUM-KLY-004",
      stockQuantity: 25,
      isFeatured: false,
      material: "Çelik, Zirkon Taş",
      weight: "3.2g",
      has3dModel: false,
      images: [{ imageUrl: "/images/products/kolye-altin-damla.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "Dönmeyen Su Yolu Kolye",
      slug: "donmeyen-su-yolu-kolye",
      categoryId: catMap.kolyeler,
      description: "Su yolu tasarımlı kolye, lake kaplama ile üretilmiştir. Ayarlanabilir boyut özelliği ile her bedene uyum sağlar.",
      shortDescription: "Su yolu tasarım, lake kaplama, ayarlanabilir",
      price: 3000,
      sku: "LUM-KLY-005",
      stockQuantity: 5,
      isFeatured: true,
      material: "925 Ayar Gümüş, Lake Kaplama",
      weight: "6.5g",
      has3dModel: true,
      images: [{ imageUrl: "/images/products/kolye-ay-isigi.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "Eyes of Collection Kolye",
      slug: "eyes-of-collection-kolye",
      categoryId: catMap.kolyeler,
      description: "by collection imzalı göz motifli kolye. Ayarlanabilir zincir ile her boyuna uyum sağlar. Günlük ve özel günler için ideal.",
      shortDescription: "Göz motifli, ayarlanabilir kolye",
      price: 480,
      sku: "LUM-KLY-006",
      stockQuantity: 18,
      isFeatured: false,
      material: "Çelik, Altın Kaplama",
      weight: "2.8g",
      has3dModel: false,
      images: [{ imageUrl: "/images/products/kolye-kalp-elmas.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "Rêve de Perles Kolye",
      slug: "reve-de-perles-kolye",
      categoryId: catMap.kolyeler,
      description: "İnci ilhamlı zarif kolye tasarımı. Fransız estetiğinden ilham alan bu parça, klasik ve modern çizgileri bir arada sunar.",
      shortDescription: "İnci ilhamlı Fransız esintili kolye",
      price: 450,
      sku: "LUM-KLY-007",
      stockQuantity: 22,
      isFeatured: false,
      material: "Çelik, İnci Detay",
      weight: "3.0g",
      has3dModel: false,
      images: [{ imageUrl: "/images/products/kolye-altin-damla.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "Star Choker Kolye",
      slug: "star-choker-kolye",
      categoryId: catMap.kolyeler,
      description: "Yıldız temalı choker kolye. Boğaza oturan tasarımıyla cesur ve şık bir görünüm sunar.",
      shortDescription: "Yıldız temalı choker kolye",
      price: 750,
      sku: "LUM-KLY-008",
      stockQuantity: 12,
      isFeatured: false,
      material: "Çelik",
      weight: "4.5g",
      has3dModel: false,
      images: [{ imageUrl: "/images/products/kolye-ay-isigi.svg", isPrimary: true }],
      variants: [],
    },

    // ── KÜPELER ──
    {
      name: "Racket Küpe",
      slug: "racket-kupe",
      categoryId: catMap.kupeler,
      description: "925 Ayar Gümüş Özel Tasarım Tenis Raketi Küpesi. Zirkon taş detaylarıyla göz alıcı bir parça.",
      shortDescription: "925 ayar gümüş tenis raketi küpe",
      price: 1400,
      sku: "LUM-KPE-001",
      stockQuantity: 8,
      isFeatured: true,
      material: "925 Ayar Gümüş, Zirkon Taş",
      weight: "3.5g",
      has3dModel: true,
      images: [{ imageUrl: "/images/products/kupe-damla-altin.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "Leopar Hoop Küpe",
      slug: "leopar-hoop-kupe",
      categoryId: catMap.kupeler,
      description: "Rodyum kaplama zirkon taşlı hoop küpe. Leopar deseninin cesur yorumu.",
      shortDescription: "Rodyum kaplama, zirkon taş, hoop tasarım",
      price: 850,
      sku: "LUM-KPE-002",
      stockQuantity: 14,
      isFeatured: true,
      material: "Rodyum Kaplama, Zirkon Taş",
      weight: "4.2g",
      has3dModel: true,
      images: [{ imageUrl: "/images/products/kupe-halka-ince.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "Adoré Küpe",
      slug: "adore-kupe",
      categoryId: catMap.kupeler,
      description: "El yapımı kalp formunda küpe. Romantik ve zarif tasarımıyla her anınıza eşlik eder.",
      shortDescription: "El yapımı kalp formunda küpe",
      price: 450,
      sku: "LUM-KPE-003",
      stockQuantity: 20,
      isFeatured: false,
      material: "Çelik, Altın Kaplama",
      weight: "2.1g",
      has3dModel: false,
      images: [{ imageUrl: "/images/products/kupe-damla-altin.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "Nevada Renkli Küpeler",
      slug: "nevada-renkli-kupeler",
      categoryId: catMap.kupeler,
      description: "Dört farklı renk seçeneğiyle Nevada küpeler. Enerjik ve renkli bir tarz arayanlar için.",
      shortDescription: "4 renk seçenekli renkli küpe",
      price: 350,
      sku: "LUM-KPE-004",
      stockQuantity: 30,
      isFeatured: false,
      material: "Çelik",
      weight: "1.8g",
      has3dModel: false,
      images: [{ imageUrl: "/images/products/kupe-halka-ince.svg", isPrimary: true }],
      variants: [
        { name: "Pembe", variantType: "color", priceModifier: 0, stockQuantity: 8 },
        { name: "Okyanus Mavisi", variantType: "color", priceModifier: 0, stockQuantity: 8 },
        { name: "Sarı", variantType: "color", priceModifier: 0, stockQuantity: 8 },
        { name: "Siyah", variantType: "color", priceModifier: 0, stockQuantity: 6 },
      ],
    },
    {
      name: "Carapace Eyes Küpe",
      slug: "carapace-eyes-kupe",
      categoryId: catMap.kupeler,
      description: "Göz motifli statement küpe. Cesur ve etkileyici tasarımıyla tüm bakışları üzerinize çeker.",
      shortDescription: "Göz motifli statement küpe",
      price: 1800,
      sku: "LUM-KPE-005",
      stockQuantity: 6,
      isFeatured: true,
      material: "925 Ayar Gümüş",
      weight: "5.8g",
      has3dModel: true,
      images: [{ imageUrl: "/images/products/kupe-damla-altin.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "Just Pearl Küpe",
      slug: "just-pearl-kupe",
      categoryId: catMap.kupeler,
      description: "İnci tarzı premium küpe. Klasik zarafeti modern dokunuşlarla birleştiren zamansız bir parça.",
      shortDescription: "İnci tarzı premium küpe",
      price: 2000,
      sku: "LUM-KPE-006",
      stockQuantity: 5,
      isFeatured: true,
      material: "925 Ayar Gümüş, Suni İnci",
      weight: "4.8g",
      has3dModel: true,
      images: [{ imageUrl: "/images/products/kupe-halka-ince.svg", isPrimary: true }],
      variants: [],
    },

    // ── BİLEKLİKLER ──
    {
      name: "Klasik Su Yolu Tennis Bileklik",
      slug: "klasik-su-yolu-tennis-bileklik",
      categoryId: catMap.bileklikler,
      description: "Su Tenis Bileklik Yolu – 925 Ayar Gümüş. Akıcı minimal tasarımıyla her tarza uyum sağlayan zarif bir parça.",
      shortDescription: "925 ayar gümüş su yolu tennis bileklik",
      price: 1950,
      sku: "LUM-BLK-001",
      stockQuantity: 10,
      isFeatured: true,
      material: "925 Ayar Gümüş",
      weight: "8.5g",
      has3dModel: false,
      images: [{ imageUrl: "/images/products/bileklik-zincir-altin.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "Kleopatra Bileklik",
      slug: "kleopatra-bileklik",
      categoryId: catMap.bileklikler,
      description: "Bronz el yapımı, altın kaplama bileklik. Suya ve denize dayanıklı tasarımıyla her an yanınızda.",
      shortDescription: "El yapımı bronz, altın kaplama, suya dayanıklı",
      price: 2200,
      sku: "LUM-BLK-002",
      stockQuantity: 7,
      isFeatured: true,
      material: "Bronz, Altın Kaplama",
      weight: "12g",
      has3dModel: false,
      images: [{ imageUrl: "/images/products/bileklik-charm.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "Perle Bileklik",
      slug: "perle-bileklik",
      categoryId: catMap.bileklikler,
      description: "El yapımı ürün, suni inci detaylı bileklik. Suya ve denize dayanıklı özel tasarım.",
      shortDescription: "El yapımı, suni inci detaylı, suya dayanıklı",
      price: 2100,
      sku: "LUM-BLK-003",
      stockQuantity: 8,
      isFeatured: true,
      material: "Bronz, Altın Kaplama, Suni İnci",
      weight: "10g",
      has3dModel: false,
      images: [{ imageUrl: "/images/products/bileklik-inci-sira.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "Eyes of Collection Bileklik",
      slug: "eyes-of-collection-bileklik",
      categoryId: catMap.bileklikler,
      description: "Ayarlanabilir boyut, zirkon taş detaylı çelik bileklik. Altın kaplama ile kalıcı parlaklık.",
      shortDescription: "Zirkon taş detaylı, ayarlanabilir çelik bileklik",
      price: 650,
      sku: "LUM-BLK-004",
      stockQuantity: 15,
      isFeatured: false,
      material: "Çelik, Altın Kaplama, Zirkon Taş",
      weight: "6g",
      has3dModel: false,
      images: [{ imageUrl: "/images/products/bileklik-zincir-altin.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "Merveilleuse Bileklik",
      slug: "merveilleuse-bileklik",
      categoryId: catMap.bileklikler,
      description: "El yapımı premium bileklik. Özel kaplamasıyla uzun ömürlü parlaklık sunar.",
      shortDescription: "El yapımı premium bileklik",
      price: 2500,
      sku: "LUM-BLK-005",
      stockQuantity: 4,
      isFeatured: true,
      material: "Bronz, Altın Kaplama",
      weight: "14g",
      has3dModel: false,
      images: [{ imageUrl: "/images/products/bileklik-charm.svg", isPrimary: true }],
      variants: [],
    },

    // ── YÜZÜKLER ──
    {
      name: "Top Spin Yüzük",
      slug: "top-spin-yuzuk",
      categoryId: catMap.yuzukler,
      description: "925 ayar gümüşten üretilen Top Spin yüzük. Işığı yansıtan modern ve zarif tasarımıyla fark yaratır.",
      shortDescription: "925 ayar gümüş, modern zarif tasarım",
      price: 650,
      sku: "LUM-YZK-001",
      stockQuantity: 18,
      isFeatured: true,
      material: "925 Ayar Gümüş",
      weight: "3.5g",
      has3dModel: true,
      images: [{ imageUrl: "/images/products/yuzuk-sonsuzluk.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "Éva Yüzük",
      slug: "eva-yuzuk",
      categoryId: catMap.yuzukler,
      description: "Özel tasarım tek taş yüzük. Ayarlanabilir beden özelliğiyle her parmağa uyum sağlar. Zirkon taş kullanılmıştır.",
      shortDescription: "Tek taş, ayarlanabilir beden, zirkon taş",
      price: 450,
      sku: "LUM-YZK-002",
      stockQuantity: 22,
      isFeatured: true,
      material: "Çelik, Zirkon Taş",
      weight: "2.8g",
      has3dModel: true,
      images: [{ imageUrl: "/images/products/yuzuk-tas-pinar.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "Monde des Perles Yüzük",
      slug: "monde-des-perles-yuzuk",
      categoryId: catMap.yuzukler,
      description: "İnci dünyasından ilham alan zarif yüzük. Ayarlanabilir beden özelliğiyle rahat kullanım sunar.",
      shortDescription: "İnci ilhamlı, ayarlanabilir beden yüzük",
      price: 510,
      sku: "LUM-YZK-003",
      stockQuantity: 16,
      isFeatured: false,
      material: "Çelik, Suni İnci",
      weight: "3.2g",
      has3dModel: true,
      images: [{ imageUrl: "/images/products/yuzuk-vintage-safir.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "Collection Çiçek Yüzük",
      slug: "collection-cicek-yuzuk",
      categoryId: catMap.yuzukler,
      description: "Çiçek tasarımlı by collection imzalı yüzük. Feminen ve zarif çizgileriyle dikkat çeker.",
      shortDescription: "Çiçek tasarımlı zarif yüzük",
      price: 440,
      sku: "LUM-YZK-004",
      stockQuantity: 20,
      isFeatured: false,
      material: "Çelik, Altın Kaplama",
      weight: "2.5g",
      has3dModel: true,
      images: [{ imageUrl: "/images/products/yuzuk-sonsuzluk.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "The Shimmer Yüzük",
      slug: "the-shimmer-yuzuk",
      categoryId: catMap.yuzukler,
      description: "Işıltılı, parlak tasarıma sahip yüzük. Her açıdan ışığı yakalayan özel kesim detayları.",
      shortDescription: "Işıltılı parlak tasarım yüzük",
      price: 350,
      sku: "LUM-YZK-005",
      stockQuantity: 25,
      isFeatured: false,
      material: "Çelik",
      weight: "2.2g",
      has3dModel: true,
      images: [{ imageUrl: "/images/products/yuzuk-tas-pinar.svg", isPrimary: true }],
      variants: [],
    },

    // ── ŞAHMERAN ──
    {
      name: "Liberty Şahmeran",
      slug: "liberty-sahmeran",
      categoryId: catMap.sahmeran,
      description: "Çelik zirkon taş şahmeran bileklik. Geleneksel şahmeran formunu modern malzemelerle buluşturan cesur bir tasarım.",
      shortDescription: "Çelik zirkon taş şahmeran",
      price: 450,
      sku: "LUM-SHM-001",
      stockQuantity: 12,
      isFeatured: false,
      material: "Çelik, Zirkon Taş",
      weight: "15g",
      has3dModel: false,
      images: [{ imageUrl: "/images/products/bileklik-charm.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "Yamore Şahmeran Bileklik",
      slug: "yamore-sahmeran-bileklik",
      categoryId: catMap.sahmeran,
      description: "Yamore koleksiyonundan şahmeran bileklik. El işçiliğiyle üretilen geleneksel tasarım.",
      shortDescription: "El yapımı şahmeran bileklik",
      price: 500,
      sku: "LUM-SHM-002",
      stockQuantity: 6,
      isFeatured: false,
      material: "Çelik, El İşçiliği",
      weight: "18g",
      has3dModel: false,
      images: [{ imageUrl: "/images/products/bileklik-zincir-altin.svg", isPrimary: true }],
      variants: [],
    },
    {
      name: "Messy Çelik Şahmeran",
      slug: "messy-celik-sahmeran",
      categoryId: catMap.sahmeran,
      description: "Çelik şahmeran bileklik. Serbest ve modern yorumuyla günlük kullanıma uygun.",
      shortDescription: "Çelik şahmeran, modern tasarım",
      price: 450,
      sku: "LUM-SHM-003",
      stockQuantity: 3,
      isFeatured: false,
      material: "Çelik",
      weight: "14g",
      has3dModel: false,
      images: [{ imageUrl: "/images/products/bileklik-inci-sira.svg", isPrimary: true }],
      variants: [],
    },
  ];

  for (const prod of products) {
    await prisma.product.create({
      data: {
        name: prod.name,
        slug: prod.slug,
        categoryId: prod.categoryId,
        description: prod.description,
        shortDescription: prod.shortDescription,
        price: prod.price,
        compareAtPrice: null,
        sku: prod.sku,
        stockQuantity: prod.stockQuantity,
        isFeatured: prod.isFeatured,
        material: prod.material,
        weight: prod.weight,
        has3dModel: prod.has3dModel,
        images: {
          create: prod.images.map((img, i) => ({
            imageUrl: img.imageUrl,
            isPrimary: img.isPrimary,
            sortOrder: i,
          })),
        },
        variants: {
          create: (prod.variants || []).map((v) => ({
            name: v.name,
            variantType: v.variantType,
            priceModifier: v.priceModifier,
            stockQuantity: v.stockQuantity,
          })),
        },
      },
    });
    console.log(`  ✓ ${prod.name}`);
  }
  console.log(`\n${products.length} ürün oluşturuldu!`);

  // ═══ İNDİRİM KODLARI ═══
  await prisma.discountCode.create({
    data: {
      code: "HOSGELDIN",
      discountType: "PERCENTAGE",
      discountValue: 10,
      minOrderAmount: 500,
      isActive: true,
    },
  });
  await prisma.discountCode.create({
    data: {
      code: "BYCOL50",
      discountType: "FIXED",
      discountValue: 50,
      minOrderAmount: 300,
      maxUses: 100,
      isActive: true,
    },
  });
  console.log("İndirim kodları oluşturuldu");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
